apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: messaging-portfolio
    newName: ghcr.io/jangwanko/cloud_portfolio
    newTag: 32452a6
patches:
  - path: patches/messaging-env-lite.yaml
  - path: patches/kafka-lite.yaml
  - path: patches/kafka-topic-bootstrap-lite.yaml
  - path: patches/app-lite.yaml
  - path: patches/autoscaling-lite.yaml
