global:
  security:
    allowInsecureImages: true

postgresql:
  replicaCount: 1
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql-repmgr
    tag: 17.6.0-debian-12-r2
  username: portfolio
  password: portfolio
  database: portfolio
  repmgrPassword: repmgr-secret
  syncReplication: false
  numSynchronousReplicas: 0
  podAntiAffinityPreset: soft
  pdb:
    create: false
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: 750m
      memory: 768Mi

pgpool:
  replicaCount: 1
  image:
    registry: docker.io
    repository: bitnamilegacy/pgpool
    tag: 4.6.3-debian-12-r0
  adminUsername: admin
  adminPassword: admin-secret
  podAntiAffinityPreset: soft
  pdb:
    create: false
  numInitChildren: 16
  maxPool: 1
  childMaxConnections: 50
  reservedConnections: 2
  childLifeTime: 300
  clientIdleLimit: 60
  connectionLifeTime: 300
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

persistence:
  enabled: true
  size: 4Gi

metrics:
  enabled: false
