architecture: replication

commonConfiguration: |-
  appendonly yes
  appendfsync everysec
  save 900 1
  save 300 10
  save 60 10000

auth:
  enabled: true
  password: redis-secret

master:
  persistence:
    enabled: true
    size: 4Gi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    size: 4Gi

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  downAfterMilliseconds: 60000
  failoverTimeout: 180000
  parallelSyncs: 1

metrics:
  enabled: false
