architecture: replication

auth:
  enabled: true
  password: redis-secret

master:
  persistence:
    enabled: true
    size: 4Gi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    size: 4Gi

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 2
  downAfterMilliseconds: 60000
  failoverTimeout: 180000
  parallelSyncs: 1

metrics:
  enabled: false
