apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: messaging-app
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BASE_URL
              value: http://api.messaging-app.svc.cluster.local:8000
            - name: K6_PROFILE
              value: "single500"
            - name: K6_SINGLE_VUS
              value: "100"
            - name: STAGE_DURATION
              value: "10s"
            - name: THINK_TIME
              value: "0.05"
            - name: K6_WRITE_RESULT_FILES
              value: "false"
            - name: SEND_IDEMPOTENCY_KEY
              value: "false"
          command:
            - k6
            - run
            - /scripts/load_test_k6.js
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      volumes:
        - name: k6-script
          configMap:
            name: k6-script
