apiVersion: v1
kind: Secret
metadata:
  name: messaging-env
  namespace: messaging-app
stringData:
  APP_ENV: "k8s-demo-lite"
  APP_VERSION: "55f538c"
  DB_POOL_MIN_CONN: "1"
  DB_POOL_MAX_CONN: "4"
  POSTGRES_MIN_READY_STANDBYS: "0"
  POSTGRES_MIN_SYNC_STANDBYS: "0"
  UVICORN_WORKERS: "1"
