apiVersion: v1
kind: Secret
metadata:
  name: messaging-env
  namespace: messaging-app
stringData:
  APP_ENV: "k8s-demo-lite"
  APP_VERSION: "2eec89c"
  KAFKA_TOPIC_PARTITIONS: "3"
  KAFKA_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_MIN_INSYNC_REPLICAS: "1"
  INGRESS_RETRY_MAX_DELAY_SECONDS: "30"
  DB_POOL_MIN_CONN: "1"
  DB_POOL_MAX_CONN: "2"
  POSTGRES_MIN_READY_STANDBYS: "0"
  POSTGRES_MIN_SYNC_STANDBYS: "0"
  UVICORN_WORKERS: "1"
